import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import { AppInfobar } from "@/components/app-infobar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SidebarProvider>
          <div className="relative flex w-full max-h-dvh overflow-hidden">
            <AppSidebar />
            <main className="flex-1 my-4 me-4 px-8 pt-8 pb-4 rounded-4xl bg-card overflow-hidden">
              {children}
            </main>
            <AppInfobar
              // onStartChat={}
              className="w-1/5 my-4 me-4 overflow-hidden"
            />
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
